from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field, field_validator, ConfigDict
from datetime import datetime
from enum import Enum
from uuid import UUID
from constants import MAX_FILE_SIZE_BYTES

class UploadRequest(BaseModel):
    """
    Schema for the upload request payload.

    Attributes:
        filename (str): The name of the file to upload. Must end with .3dm.
        size (int): The size of the file in bytes. Must be greater than 0 and less than 500MB.
        checksum (Optional[str]): optional checksum of the file for integrity verification.
    """
    filename: str = Field(..., description="Name of the file to upload (must be .3dm)")
    size: int = Field(..., gt=0, description="Size in bytes")
    checksum: Optional[str] = Field(None, description="Optional checksum for validation")

    @field_validator('size')
    @classmethod
    def validate_file_size(cls, v: int) -> int:
        """
        Validate file size does not exceed 500MB (max upload limit).

        Raises:
            ValueError: If file size exceeds MAX_FILE_SIZE_BYTES constant.
        """
        if v > MAX_FILE_SIZE_BYTES:
            raise ValueError(
                f"File size {v} bytes exceeds maximum allowed size of "
                f"500MB ({MAX_FILE_SIZE_BYTES} bytes)"
            )
        return v

class UploadResponse(BaseModel):
    """
    Schema for the upload response payload.

    Attributes:
        upload_url (str): The presigned URL to upload the file to S3.
        file_id (str): The unique identifier assigned to the file.
        filename (str): The original filename.
        file_key (str): The storage path (bucket key) used to confirm the upload.
    """
    upload_url: str = Field(..., description="Presigned URL for S3 upload")
    file_id: str = Field(..., description="Unique identifier for the file")
    filename: str = Field(..., description="Original filename")
    file_key: str = Field(..., description="Storage path for upload confirmation")


# ===== T-004-BACK: Confirm Upload Schemas =====

class ConfirmUploadRequest(BaseModel):
    """
    Schema for confirming a completed file upload.

    This request is sent by the frontend after successfully uploading
    a file to the presigned URL, to trigger backend processing.

    Attributes:
        file_id (UUID): The unique identifier returned from the presigned URL request.
        file_key (str): The S3 object key where the file was uploaded.
    """
    file_id: UUID = Field(..., description="UUID of the uploaded file")
    file_key: str = Field(..., description="S3 object key (path in bucket)")


class ConfirmUploadResponse(BaseModel):
    """
    Schema for the confirm upload response.

    Attributes:
        success (bool): Whether the confirmation was successful.
        message (str): Human-readable status message.
        event_id (Optional[str]): ID of the created event record (if applicable).
        task_id (Optional[str]): ID of the launched Celery task (if applicable).
    """
    success: bool = Field(..., description="Confirmation status")
    message: str = Field(..., description="Status message")
    event_id: Optional[str] = Field(None, description="Created event record ID")
    task_id: Optional[str] = Field(None, description="Celery task ID for processing")


# ===== T-023-TEST: Validation Report Schemas =====

class ValidationErrorItem(BaseModel):
    """
    Schema for a single validation error.

    Attributes:
        category (str): Error category (e.g., "nomenclature", "geometry", "io").
        target (Optional[str]): Target element (layer name, object id, etc.).
        message (str): Human-readable error description.
    """
    category: str = Field(..., description="Error category")
    target: Optional[str] = Field(None, description="Target element identifier")
    message: str = Field(..., description="Error description")


class ValidationReport(BaseModel):
    """
    Schema for file validation report.

    This report is generated by the agent after processing a .3dm file
    and contains validation results, errors, and extracted metadata.

    Attributes:
        is_valid (bool): Whether the file passed all validation checks.
        errors (List[ValidationErrorItem]): List of validation errors found.
        metadata (Dict[str, Any]): Extracted metadata (user strings, layer info, etc.).
        validated_at (Optional[datetime]): Timestamp of validation.
        validated_by (Optional[str]): Worker or service that performed validation.
    """
    is_valid: bool = Field(..., description="Validation status")
    errors: List[ValidationErrorItem] = Field(default_factory=list, description="Validation errors")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Extracted metadata")
    validated_at: Optional[datetime] = Field(None, description="Validation timestamp")
    validated_by: Optional[str] = Field(None, description="Validator identifier")


# ===== T-030-BACK: Get Validation Status Endpoint Schemas =====

class BlockStatus(str, Enum):
    """
    Lifecycle states for blocks (parts).

    Synchronized with PostgreSQL ENUM block_status (T-021-DB).

    Valid transitions:
        uploaded -> processing -> validated | rejected | error_processing
        validated -> in_fabrication -> completed -> archived
        rejected -> uploaded (after fixes)
        error_processing -> uploaded (after manual review)
    """
    UPLOADED = "uploaded"
    PROCESSING = "processing"
    VALIDATED = "validated"
    REJECTED = "rejected"
    ERROR_PROCESSING = "error_processing"
    IN_FABRICATION = "in_fabrication"
    COMPLETED = "completed"
    ARCHIVED = "archived"


# ===== T-1503-AGENT: Material Type Enum =====

class MaterialType(str, Enum):
    """
    Material types for architectural elements (T-1503-AGENT).

    Synchronized with PostgreSQL CHECK constraint (T-1501-DB):
    CHECK (material_type IN ('Stone', 'Ceramic'))

    Valid values:
        Stone: Natural stone (99% of Sagrada Familia elements)
        Ceramic: Ceramic materials (decorative elements)
    """
    STONE = "Stone"
    CERAMIC = "Ceramic"


class ValidationStatusResponse(BaseModel):
    """
    Response schema for GET /api/parts/{id}/validation endpoint.

    Combines block metadata with validation report for frontend display.

    Attributes:
        block_id (UUID): Unique identifier of the block.
        iso_code (str): ISO code of the block (e.g., "PENDING-a1b2c3d4", "SAGR-Z1-001").
        status (BlockStatus): Current lifecycle state of the block.
        validation_report (Optional[ValidationReport]): Complete validation report (NULL if not validated yet).
        job_id (Optional[str]): Celery task ID if status=processing (for progress tracking).
    """
    block_id: UUID = Field(..., description="UUID of the block")
    iso_code: str = Field(..., description="ISO code identifier")
    status: BlockStatus = Field(..., description="Current block status")
    validation_report: Optional[ValidationReport] = Field(
        None,
        description="Validation report (NULL if not validated)"
    )
    job_id: Optional[str] = Field(
        None,
        description="Celery task ID for tracking (only if status=processing)"
    )

    model_config = ConfigDict(
        json_schema_extra={
        "example": {
        "block_id": "550e8400-e29b-41d4-a716-446655440000",
        "iso_code": "PENDING-a1b2c3d4",
        "status": "validated",
        "validation_report": {
        "is_valid": True,
        "errors": [],
        "metadata": {
        "total_objects": 42,
        "valid_objects": 42,
        "invalid_objects": 0,
        "user_strings_extracted": 15
        },
        "validated_at": "2026-02-14T23:15:00Z",
        "validated_by": "librarian-v1.0.0"
        },
        "job_id": None
        }
        }
    )
# ===== T-0501-BACK: Parts Canvas API Schemas =====

class BoundingBox(BaseModel):
    """
    3D bounding box for spatial layout in canvas.

    Used by PartCanvasItem to represent geometry bounds extracted from Rhino models.
    Format matches THREE.js Box3 structure for frontend compatibility.

    Attributes:
        min: Array of [x, y, z] coordinates for minimum corner
        max: Array of [x, y, z] coordinates for maximum corner
    """
    min: List[float] = Field(..., min_length=3, max_length=3, description="Min corner [x, y, z]")
    max: List[float] = Field(..., min_length=3, max_length=3, description="Max corner [x, y, z]")

    @field_validator('min', 'max')
    @classmethod
    def validate_coordinates(cls, v):
        if len(v) != 3:
            raise ValueError('Must contain exactly 3 coordinates [x, y, z]')
        return v

    model_config = ConfigDict(
        json_schema_extra={
        "example": {
        "min": [-2.5, 0.0, -2.5],
        "max": [2.5, 5.0, 2.5]
        }
        }
    )
class PartCanvasItem(BaseModel):
    """
    Minimal part info optimized for 3D canvas rendering.

    Contract: Must match TypeScript interface PartCanvasItem exactly.
    Used by GET /api/parts endpoint for Dashboard 3D (US-005).

    Attributes:
        id: Block UUID
        iso_code: Part identifier (ISO-19650 format, e.g., SF-C12-D-001)
        status: Lifecycle state (reuses existing BlockStatus enum)
        tipologia: Part typology (capitel, columna, dovela, clave, imposta, etc.)
        material_type: Material type (US-015: for LOD system)
        high_poly_url: Storage URL to high-detail GLB (~7k tris, ~600-800KB, LOD Level 0: 0-5m)
        mid_poly_url: Storage URL to mid-detail GLB (~2k tris, ~300-400KB, LOD Level 1: 5-20m)
        low_poly_url: Storage URL to low-detail GLB (~500 tris, ~150-200KB, LOD Level 2: 20-50m)
        bbox: 3D bounding box for camera centering, spatial queries, and LOD Level 3 (>50m proxy)
    """
    id: UUID = Field(..., description="Block UUID")
    iso_code: str = Field(..., description="Part identifier (e.g., SF-C12-D-001)")
    status: BlockStatus = Field(..., description="Lifecycle state")
    tipologia: str = Field(..., description="Part typology")
    material_type: Optional[str] = Field(None, description="Material type (Montjuïc, Gaudí, Synthetic)")
    high_poly_url: Optional[str] = Field(None, description="High-detail GLB URL (~7k tris, LOD 0-5m)")
    mid_poly_url: Optional[str] = Field(None, description="Mid-detail GLB URL (~2k tris, LOD 5-20m)")
    low_poly_url: Optional[str] = Field(None, description="Low-detail GLB URL (~500 tris, LOD 20-50m)")
    bbox: Optional[BoundingBox] = Field(None, description="3D bounding box")

    model_config = ConfigDict(
        json_schema_extra={
        "example": {
        "id": "550e8400-e29b-41d4-a716-446655440000",
        "iso_code": "SF-C12-D-001",
        "status": "validated",
        "tipologia": "capitel",
        "material_type": "Montjuïc",
        "high_poly_url": "https://xyz.supabase.co/storage/v1/object/public/processed-geometry/high-poly/550e8400.glb",
        "mid_poly_url": "https://xyz.supabase.co/storage/v1/object/public/processed-geometry/mid-poly/550e8400.glb",
        "low_poly_url": "https://xyz.supabase.co/storage/v1/object/public/processed-geometry/low-poly/550e8400.glb",
        "bbox": {"min": [-2.5, 0.0, -2.5], "max": [2.5, 5.0, 2.5]}
        }
        }
    )
class PartsListResponse(BaseModel):
    """
    Response for GET /api/parts endpoint.

    Attributes:
        parts: Array of all parts matching filters
        count: Total number of parts returned
        filters_applied: Echo of query parameters used for transparency
    """
    parts: List[PartCanvasItem] = Field(..., description="Array of canvas-ready parts")
    count: int = Field(..., description="Total count of parts returned")
    filters_applied: Dict[str, Any] = Field(default_factory=dict, description="Applied filters (for debugging)")

    model_config = ConfigDict(
        json_schema_extra={
        "example": {
        "parts": [
        {
        "id": "550e8400-e29b-41d4-a716-446655440000",
        "iso_code": "SF-C12-D-001",
        "status": "validated",
        "tipologia": "capitel",
        "low_poly_url": "https://xyz.supabase.co/storage/v1/object/public/processed-geometry/low-poly/550e8400.glb",
        "bbox": {"min": [-2.5, 0, -2.5], "max": [2.5, 5, 2.5]},
        "workshop_id": "123e4567-e89b-12d3-a456-426614174000"
        }
        ],
        "count": 1,
        "filters_applied": {
        "status": "validated",
        "tipologia": "capitel",
        "workshop_id": None
        }
        }
        }
    )
# ===== T-1002-BACK: Get Part Detail API Schemas =====

class PartDetailResponse(BaseModel):
    """
    Detailed part info for 3D viewer modal (US-010).

    Contract: Must match TypeScript interface PartDetail exactly.
    Used by GET /api/parts/{id} endpoint.

    Attributes:
        id: Block UUID
        iso_code: Part identifier (ISO-19650 format)
        status: Lifecycle state
        tipologia: Part typology
        created_at: Row creation timestamp (ISO 8601 format)
        low_poly_url: Presigned CDN URL for GLB file (TTL 5min), None if not generated yet
        bbox: 3D bounding box for camera positioning
        validation_report: Automatic validation results from The Librarian agent
        glb_size_bytes: File size of GLB in bytes (optional, from validation metadata)
        triangle_count: Number of triangles (optional, from validation metadata)
    """
    id: UUID = Field(..., description="Block UUID")
    iso_code: str = Field(..., description="Part identifier (e.g., SF-C12-D-001)")
    status: BlockStatus = Field(..., description="Lifecycle state")
    tipologia: str = Field(..., description="Part typology (capitel, columna, dovela, etc.)")
    created_at: str = Field(..., description="Creation timestamp (ISO 8601)")
    low_poly_url: Optional[str] = Field(None, description="Presigned CDN URL for GLB (TTL 5min)")
    bbox: Optional[BoundingBox] = Field(None, description="3D bounding box")
    validation_report: Optional[ValidationReport] = Field(None, description="Validation results from agent")
    glb_size_bytes: Optional[int] = Field(None, description="GLB file size in bytes")
    triangle_count: Optional[int] = Field(None, description="Triangle count (for performance)")

    model_config = ConfigDict(
        json_schema_extra={
        "example": {
        "id": "550e8400-e29b-41d4-a716-446655440000",
        "iso_code": "SF-C12-D-001",
        "status": "validated",
        "tipologia": "capitel",
        "created_at": "2026-02-15T10:30:00Z",
        "low_poly_url": "https://d1234abcd.cloudfront.net/low-poly/550e8400.glb?X-Amz-Expires=300&...",
        "bbox": {"min": [-2.5, 0.0, -2.5], "max": [2.5, 5.0, 2.5]},
        "validation_report": {
        "is_valid": True,
        "errors": [],
        "metadata": {"layer_count": 5, "object_count": 12}
        },
        "glb_size_bytes": 425984,
        "triangle_count": 1024
        }
        }
    )
# ===== T-1003-BACK: Part Navigation API Schemas =====

class PartNavigationResponse(BaseModel):
    """
    Response for GET /api/parts/{id}/adjacent endpoint.

    Provides prev/next IDs for sequential navigation between parts in the 3D viewer modal.
    Order is determined by created_at ASC (oldest first), with filters applied.

    Contract: Must match TypeScript interface PartNavigationResponse exactly.
    Used by US-010 for Prev/Next buttons in modal footer.

    Attributes:
        prev_id: UUID of previous part in sequence (None if current is first)
        next_id: UUID of next part in sequence (None if current is last)
        current_index: 1-based position of current part in filtered set (e.g., 42 of 150)
        total_count: Total number of parts in filtered set
    """
    prev_id: Optional[UUID] = Field(None, description="Previous part UUID (None if first)")
    next_id: Optional[UUID] = Field(None, description="Next part UUID (None if last)")
    current_index: int = Field(..., ge=1, description="1-based index of current part")
    total_count: int = Field(..., ge=0, description="Total parts in filtered set")

    model_config = ConfigDict(
        json_schema_extra={
        "example": {
        "prev_id": "123e4567-e89b-12d3-a456-426614174000",
        "next_id": "987fcdeb-51a2-43e7-9876-543210fedcba",
        "current_index": 42,
        "total_count": 150
        }
        }
    )
# ===== T-1504-BACK: Element API Schemas (US-015 Refactoring) =====

class ElementStatus(str, Enum):
    """
    Lifecycle states for elements (renamed from BlockStatus for internationalization).

    Synchronized with PostgreSQL ENUM block_status (T-021-DB).

    Valid transitions:
        uploaded -> processing -> validated | rejected | error_processing
        validated -> in_fabrication -> completed -> archived
        rejected -> uploaded (after fixes)
        error_processing -> uploaded (after manual review)
    """
    UPLOADED = "uploaded"
    PROCESSING = "processing"
    VALIDATED = "validated"
    REJECTED = "rejected"
    ERROR_PROCESSING = "error_processing"
    IN_FABRICATION = "in_fabrication"
    COMPLETED = "completed"
    ARCHIVED = "archived"


class Element(BaseModel):
    """
    Element schema optimized for 3D canvas rendering (US-005 + US-015 LOD).

    Contract: Must match TypeScript interface Element exactly (T-1505-FRONT).

    Breaking Changes from PartCanvasItem:
    - Removed: workshop_id, workshop_name (workshops not used in MVP)
    - Renamed: tipologia → material_type (internationalization)
    - Changed: material_type from enum to str (validated against 62 real materials)

    LOD System (US-015):
    - 4-level LOD: high_poly (0-5m), mid_poly (5-20m), low_poly (20-50m), bbox (>50m)
    - URLs are CDN-transformed presigned URLs to GLB files

    Attributes:
        id: Element UUID
        iso_code: ISO-19650 identifier (e.g., GLPER.B-PAE0720.0701)
        status: Lifecycle state (ElementStatus enum)
        material_type: Stone material type (validated against 62 MATERIAL_COLORS)
        high_poly_url: CDN URL to high-detail GLB (~7k tris, Level 0: 0-5m viewing)
        mid_poly_url: CDN URL to mid-detail GLB (~2k tris, Level 1: 5-20m viewing)
        low_poly_url: CDN URL to low-detail GLB (~500 tris, Level 2: 20-50m viewing)
        bbox: 3D bounding box for camera centering and LOD Level 3 (>50m wireframe proxy)
    """
    id: UUID = Field(..., description="Element UUID")
    iso_code: str = Field(..., description="ISO-19650 identifier (e.g., GLPER.B-PAE0720.0701)")
    status: ElementStatus = Field(..., description="Lifecycle state")
    material_type: str = Field(
        ...,
        description="Stone material type (one of 62 real materials: Montjuïc, Ulldecona, etc.)"
    )
    high_poly_url: Optional[str] = Field(
        None,
        description="CDN URL to high-detail GLB (~7k tris, LOD Level 0: 0-5m viewing distance)"
    )
    mid_poly_url: Optional[str] = Field(
        None,
        description="CDN URL to mid-detail GLB (~2k tris, LOD Level 1: 5-20m viewing distance)"
    )
    low_poly_url: Optional[str] = Field(
        None,
        description="CDN URL to low-detail GLB (~500 tris, LOD Level 2: 20-50m viewing distance)"
    )
    bbox: Optional[BoundingBox] = Field(
        None,
        description="3D bounding box (used for camera centering and LOD Level 3: >50m wireframe proxy)"
    )

    @field_validator('material_type')
    @classmethod
    def validate_material_type(cls, v: str) -> str:
        """
        Validate material_type against MATERIAL_COLORS dictionary (62 real materials).

        Args:
            v: Material type string from database

        Returns:
            Validated material type

        Raises:
            ValueError: If material not in VALID_MATERIALS list
        """
        from agent.constants import VALID_MATERIALS

        if v not in VALID_MATERIALS:
            raise ValueError(
                f"Invalid material_type: '{v}'. Must be one of {len(VALID_MATERIALS)} "
                f"valid materials (e.g., Montjuïc, Ulldecona, Floresta). "
                f"See agent.constants.MATERIAL_COLORS for full list."
            )
        return v

    model_config = ConfigDict(
        json_schema_extra={
        "example": {
        "id": "550e8400-e29b-41d4-a716-446655440000",
        "iso_code": "GLPER.B-PAE0720.0701",
        "status": "validated",
        "material_type": "Montjuïc",
        "high_poly_url": "https://d1234abcd.cloudfront.net/models/high-poly/550e8400_20260307T120000Z.glb",
        "mid_poly_url": "https://d1234abcd.cloudfront.net/models/mid-poly/550e8400_20260307T120000Z.glb",
        "low_poly_url": "https://d1234abcd.cloudfront.net/models/low-poly/550e8400_20260307T120000Z.glb",
        "bbox": {"min": [-0.35, -0.70, -0.35], "max": [0.35, 0.70, 0.35]}
        }
        }
    )
class ElementsListResponse(BaseModel):
    """
    Response for GET /api/elements endpoint.

    Breaking Changes from PartsListResponse:
    - Renamed: parts → elements
    - Removed: count (redundant, use len(elements))

    Attributes:
        elements: Array of all elements matching filters
        filters_applied: Echo of query parameters for transparency
        meta: Metadata (total count, filtered count)
    """
    elements: List[Element] = Field(..., description="Array of canvas-ready elements")
    filters_applied: dict = Field(default_factory=dict, description="Applied filters (debugging)")
    meta: dict = Field(
        default_factory=lambda: {"total": 0, "filtered": 0},
        description="Response metadata"
    )

    model_config = ConfigDict(
        json_schema_extra={
        "example": {
        "elements": [
        {
        "id": "550e8400-e29b-41d4-a716-446655440000",
        "iso_code": "GLPER.B-PAE0720.0701",
        "status": "validated",
        "material_type": "Montjuïc",
        "low_poly_url": "https://d1234abcd.cloudfront.net/models/low-poly/550e8400.glb",
        "bbox": {"min": [-0.35, -0.70, -0.35], "max": [0.35, 0.70, 0.35]}
        }
        ],
        "filters_applied": {"status": "validated", "material_type": "Montjuïc"},
        "meta": {"total": 6, "filtered": 6}
        }
        }
    )
class ElementDetail(BaseModel):
    """
    Detailed element info for 3D viewer modal (US-010).

    Contract: Must match TypeScript interface ElementDetail exactly (T-1505-FRONT).

    Breaking Changes from PartDetailResponse:
    - Removed: workshop_id, workshop_name, tipologia
    - Added: material_type (str validated against 62 materials)

    Attributes:
        id: Element UUID
        iso_code: ISO-19650 identifier
        status: Lifecycle state
        material_type: Stone material type
        created_at: Row creation timestamp (ISO 8601)
        low_poly_url: Presigned CDN URL (TTL 5min)
        bbox: 3D bounding box
        validation_report: Validation results from The Librarian
        glb_size_bytes: GLB file size (optional)
        triangle_count: Triangle count (optional)
    """
    id: UUID = Field(..., description="Element UUID")
    iso_code: str = Field(..., description="ISO-19650 identifier")
    status: ElementStatus = Field(..., description="Lifecycle state")
    material_type: str = Field(..., description="Stone material type (62 options)")
    created_at: str = Field(..., description="Creation timestamp (ISO 8601)")
    updated_at: Optional[str] = Field(None, description="Last update timestamp (ISO 8601)")
    low_poly_url: Optional[str] = Field(None, description="Presigned CDN URL (TTL 5min)")
    bbox: Optional[BoundingBox] = Field(None, description="3D bounding box")
    validation_report: Optional[ValidationReport] = Field(None, description="Validation results")
    glb_size_bytes: Optional[int] = Field(None, description="GLB file size in bytes")
    triangle_count: Optional[int] = Field(None, description="Triangle count (performance)")
    rhino_metadata: Optional[dict] = Field(None, description="Rhino 3DM metadata (JSONB)")

    @field_validator('material_type')
    @classmethod
    def validate_material_type(cls, v: str) -> str:
        """Validate material_type against 62 real materials."""
        from agent.constants import VALID_MATERIALS

        if v not in VALID_MATERIALS:
            raise ValueError(f"Invalid material_type: '{v}'. Must be one of {len(VALID_MATERIALS)} valid materials.")
        return v

    model_config = ConfigDict(
        json_schema_extra={
        "example": {
        "id": "550e8400-e29b-41d4-a716-446655440000",
        "iso_code": "GLPER.B-PAE0720.0701",
        "status": "validated",
        "material_type": "Montjuïc",
        "created_at": "2026-03-06T10:30:00Z",
        "low_poly_url": "https://d1234abcd.cloudfront.net/models/low-poly/550e8400.glb",
        "bbox": {"min": [-0.35, -0.70, -0.35], "max": [0.35, 0.70, 0.35]},
        "validation_report": {
        "is_valid": True,
        "errors": [],
        "metadata": {"layer_count": 1, "object_count": 1}
        },
        "glb_size_bytes": 312456,
        "triangle_count": 987,
        "rhino_metadata": {
            "userstrings": {"Codi": "GLPER.B-PAE0720.0701", "Material": "Montjuïc"},
            "geometry_type": "InstanceReference"
        }
        }
        }
    )
class ElementNavigationResponse(BaseModel):
    """
    Response for GET /api/elements/{id}/navigation endpoint.

    No breaking changes in structure, only renamed class for consistency.
    """
    prev_id: Optional[UUID] = Field(None, description="Previous element UUID (None if first)")
    next_id: Optional[UUID] = Field(None, description="Next element UUID (None if last)")
    current_index: int = Field(..., ge=1, description="1-based index of current element")
    total_count: int = Field(..., ge=0, description="Total elements in filtered set")

    model_config = ConfigDict(
        json_schema_extra={
        "example": {
        "prev_id": "123e4567-e89b-12d3-a456-426614174000",
        "next_id": "987fcdeb-51a2-43e7-9876-543210fedcba",
        "current_index": 42,
        "total_count": 150
        }
        }
    )
