from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime

class UploadRequest(BaseModel):
    """
    Schema for the upload request payload.

    Attributes:
        filename (str): The name of the file to upload. Must end with .3dm.
        size (int): The size of the file in bytes. Must be greater than 0.
        checksum (Optional[str]): optional checksum of the file for integrity verification.
    """
    filename: str = Field(..., description="Name of the file to upload (must be .3dm)")
    size: int = Field(..., gt=0, description="Size in bytes")
    checksum: Optional[str] = Field(None, description="Optional checksum for validation")

class UploadResponse(BaseModel):
    """
    Schema for the upload response payload.

    Attributes:
        upload_url (str): The presigned URL to upload the file to S3.
        file_id (str): The unique identifier assigned to the file.
        filename (str): The original filename.
    """
    upload_url: str = Field(..., description="Presigned URL for S3 upload")
    file_id: str = Field(..., description="Unique identifier for the file")
    filename: str = Field(..., description="Original filename")


# ===== T-004-BACK: Confirm Upload Schemas =====

class ConfirmUploadRequest(BaseModel):
    """
    Schema for confirming a completed file upload.
    
    This request is sent by the frontend after successfully uploading
    a file to the presigned URL, to trigger backend processing.

    Attributes:
        file_id (str): The unique identifier returned from the presigned URL request.
        file_key (str): The S3 object key where the file was uploaded.
    """
    file_id: str = Field(..., description="UUID of the uploaded file")
    file_key: str = Field(..., description="S3 object key (path in bucket)")


class ConfirmUploadResponse(BaseModel):
    """
    Schema for the confirm upload response.
    
    Attributes:
        success (bool): Whether the confirmation was successful.
        message (str): Human-readable status message.
        event_id (Optional[str]): ID of the created event record (if applicable).
        task_id (Optional[str]): ID of the launched Celery task (if applicable).
    """
    success: bool = Field(..., description="Confirmation status")
    message: str = Field(..., description="Status message")
    event_id: Optional[str] = Field(None, description="Created event record ID")
    task_id: Optional[str] = Field(None, description="Celery task ID for processing")


# ===== T-023-TEST: Validation Report Schemas =====

class ValidationErrorItem(BaseModel):
    """
    Schema for a single validation error.
    
    Attributes:
        category (str): Error category (e.g., "nomenclature", "geometry", "io").
        target (Optional[str]): Target element (layer name, object id, etc.).
        message (str): Human-readable error description.
    """
    category: str = Field(..., description="Error category")
    target: Optional[str] = Field(None, description="Target element identifier")
    message: str = Field(..., description="Error description")


class ValidationReport(BaseModel):
    """
    Schema for file validation report.
    
    This report is generated by the agent after processing a .3dm file
    and contains validation results, errors, and extracted metadata.
    
    Attributes:
        is_valid (bool): Whether the file passed all validation checks.
        errors (List[ValidationErrorItem]): List of validation errors found.
        metadata (Dict[str, Any]): Extracted metadata (user strings, layer info, etc.).
        validated_at (Optional[datetime]): Timestamp of validation.
        validated_by (Optional[str]): Worker or service that performed validation.
    """
    is_valid: bool = Field(..., description="Validation status")
    errors: List[ValidationErrorItem] = Field(default_factory=list, description="Validation errors")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Extracted metadata")
    validated_at: Optional[datetime] = Field(None, description="Validation timestamp")
    validated_by: Optional[str] = Field(None, description="Validator identifier")

