-- Migration: LOD System - Multi-Level Geometry Assets
-- Date: 2026-03-11
-- Ticket: US-015 (CAD Navigation + Real LOD System)
-- Purpose: Add high_poly_url and mid_poly_url columns for 3-level LOD system
--
-- ARCHITECTURE OVERVIEW:
-- =====================
-- Current State: 1 level (low_poly_url ~1000 faces)
-- New State: 3 levels + BBox proxy
--   - high_poly_url: ~5000-8000 faces (0-5m viewing distance)
--   - mid_poly_url:  ~1500-2000 faces (5-20m viewing distance)  
--   - low_poly_url:  ~400-600 faces (20-50m viewing distance)
--   - bbox (JSON):   12 triangles (>50m viewing distance)
--
-- BENEFITS:
-- - High-quality inspection at close range (high-poly)
-- - Balanced performance for normal work (mid-poly)
-- - Maximum optimization for overview (low-poly + bbox)
-- - Progressive loading with Three.js LOD system
--
-- COMPATIBILITY:
-- - Backward compatible: existing low_poly_url values preserved
-- - Frontend fallback: mid_poly → low_poly if mid_poly_url IS NULL
-- - Async processing: new columns nullable until reprocesamiento completes

BEGIN;

-- =============================================================================
-- STEP 1: Add new LOD level columns
-- =============================================================================

ALTER TABLE blocks 
  ADD COLUMN IF NOT EXISTS high_poly_url TEXT NULL,
  ADD COLUMN IF NOT EXISTS mid_poly_url TEXT NULL;

-- Column comments for documentation
COMMENT ON COLUMN blocks.high_poly_url IS 
  'High-poly GLB URL (~5000-8000 faces, Draco compressed ~600-800KB). Viewing distance: 0-5m. Generated by T-0502-AGENT with no decimation.';

COMMENT ON COLUMN blocks.mid_poly_url IS 
  'Mid-poly GLB URL (~1500-2000 faces, Draco compressed ~300-400KB). Viewing distance: 5-20m. Generated by T-0502-AGENT with moderate decimation (~70-80% face reduction).';

COMMENT ON COLUMN blocks.low_poly_url IS 
  'Low-poly GLB URL (~400-600 faces, Draco compressed ~150-200KB). Viewing distance: 20-50m. Generated by T-0502-AGENT with aggressive decimation (~90-95% face reduction).';

-- =============================================================================
-- STEP 2: Create optimization indexes
-- =============================================================================

-- Index for LOD completeness check (all 3 levels ready)
CREATE INDEX IF NOT EXISTS idx_blocks_lod_complete ON blocks(id) 
  WHERE high_poly_url IS NOT NULL 
    AND mid_poly_url IS NOT NULL 
    AND low_poly_url IS NOT NULL
    AND bbox IS NOT NULL
    AND is_archived = false;

COMMENT ON INDEX idx_blocks_lod_complete IS 
  'Fast query for blocks with complete LOD chain (high/mid/low + bbox). Used by frontend Dashboard3D to filter renderable elements.';

-- Index for LOD processing queue (find blocks needing LOD generation)
CREATE INDEX IF NOT EXISTS idx_blocks_lod_pending ON blocks(status, created_at) 
  WHERE low_poly_url IS NOT NULL 
    AND (high_poly_url IS NULL OR mid_poly_url IS NULL)
    AND is_archived = false;

COMMENT ON INDEX idx_blocks_lod_pending IS 
  'Identify blocks with low_poly_url but missing high/mid levels. Used by reprocesamiento script to prioritize LOD generation queue.';

-- =============================================================================
-- STEP 3: Validation checks
-- =============================================================================

DO $$
DECLARE
    col_count INTEGER;
    idx_count INTEGER;
BEGIN
    -- Verify columns exist
    SELECT COUNT(*) INTO col_count
    FROM information_schema.columns
    WHERE table_name = 'blocks'
        AND table_schema = 'public'
        AND column_name IN ('high_poly_url', 'mid_poly_url', 'low_poly_url', 'bbox');
    
    IF col_count <> 4 THEN
        RAISE EXCEPTION 'Migration failed: Expected 4 columns (high_poly_url, mid_poly_url, low_poly_url, bbox), found %', col_count;
    END IF;

    -- Verify indexes exist
    SELECT COUNT(*) INTO idx_count
    FROM pg_indexes
    WHERE tablename = 'blocks'
        AND schemaname = 'public'
        AND indexname IN ('idx_blocks_lod_complete', 'idx_blocks_lod_pending');
    
    IF idx_count <> 2 THEN
        RAISE EXCEPTION 'Migration failed: Expected 2 indexes (idx_blocks_lod_complete, idx_blocks_lod_pending), found %', idx_count;
    END IF;

    RAISE NOTICE '✅ Migration successful: high_poly_url & mid_poly_url columns + 2 optimization indexes created';
    RAISE NOTICE '📊 Existing data: % blocks with low_poly_url (backward compatible)', 
        (SELECT COUNT(*) FROM blocks WHERE low_poly_url IS NOT NULL);
    RAISE NOTICE '⏳ Next step: Run reprocesamiento script to generate high/mid LOD levels';
END $$;

COMMIT;

-- =============================================================================
-- ROLLBACK INSTRUCTIONS (for emergency use)
-- =============================================================================
-- DROP INDEX IF EXISTS idx_blocks_lod_pending;
-- DROP INDEX IF EXISTS idx_blocks_lod_complete;
-- ALTER TABLE blocks DROP COLUMN IF EXISTS mid_poly_url;
-- ALTER TABLE blocks DROP COLUMN IF EXISTS high_poly_url;
