-- Migration: Add mtl_url column to blocks table
-- Purpose: Store the companion .mtl file URL for per-face Rhino layer colors
-- Generated by: SF-PM geometry pipeline (OBJ+MTL with Rhino layer colors)
-- Frontend: Used by MTLLoader when color mode is 'layer'

ALTER TABLE blocks
    ADD COLUMN IF NOT EXISTS mtl_url TEXT;

COMMENT ON COLUMN blocks.mtl_url IS
    'Public URL of companion .mtl file for high-poly OBJ. Contains per-face Rhino layer colors. NULL when layer colors are absent or trivial (all black).';
